### ISSUE TITLE
可以不搭配MySQL而使用sqlite数据库吗

### ISSUE THREAD

**Issue by luckypoem** [griffin702/ginana-blog#1]
如题

**Comment by griffin702** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    暂没有支持其他数据库
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                117976509
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2021年8月10日 ***@***.***> 写道： 




如题



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
